"""Add HUD PRAC compliance tables

Revision ID: cd00289c535c
Revises: a97241fe8aa7
Create Date: 2025-10-24 22:17:47.238141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd00289c535c'
down_revision: Union[str, None] = 'a97241fe8aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
