"""Rename HUD household member relationship column to relationship_type

Revision ID: db50891cf06b
Revises: e535612bde08
Create Date: 2025-10-24 22:23:36.377222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db50891cf06b'
down_revision: Union[str, None] = 'e535612bde08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
